[workspace]
authors = ["eric-santos22 <ericduarteds@gmail.com>"]
channels = ["conda-forge"]
name = "downloader_project"
platforms = ["win-64"]
version = "0.1.0"

[tasks]

[dependencies]
qgis = ">=3.44.7,<4"
pyqt = ">=5.15.11,<6"
loguru = ">=0.7.3,<0.8"
