# -*- coding: utf-8 -*-
"""
/***************************************************************************
 downloaderPlugin
                                 A QGIS plugin
 This plugin downloads a file from a URL and saves it on a specified path.
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                             -------------------
        begin                : 2026-03-25
        copyright            : (C) 2026 by Eric Duarte dos Santos
        email                : ericsantos@ime.eb.br
        git sha              : $Format:%H$
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
 This script initializes the plugin, making it known to QGIS.
"""


# noinspection PyPep8Naming
def classFactory(iface):  # pylint: disable=invalid-name
    """Load downloaderPlugin class from file downloaderPlugin.

    :param iface: A QGIS interface instance.
    :type iface: QgsInterface
    """
    #
    from .downloaderPlugin import downloaderPlugin
    return downloaderPlugin(iface)
