# -*- coding: utf-8 -*-
"""
/***************************************************************************
 downloaderPluginDialog
                                 A QGIS plugin
 This plugin downloads a file from a URL and saves it on a specified path.
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                             -------------------
        begin                : 2026-03-25
        git sha              : $Format:%H$
        copyright            : (C) 2026 by Eric Duarte dos Santos
        email                : ericsantos@ime.eb.br
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
"""

import os

from qgis.PyQt import uic
from qgis.PyQt import QtWidgets
from qgis.core import QgsVectorLayer, QgsProject
from qgis.PyQt.QtWidgets import QApplication
from .downloader_class import Downloader
# This loads your .ui file so that PyQt can populate your plugin with the elements from Qt Designer
FORM_CLASS, _ = uic.loadUiType(os.path.join(
    os.path.dirname(__file__), 'downloaderPlugin_dialog_base.ui'))


class downloaderPluginDialog(QtWidgets.QDialog, FORM_CLASS):
    def __init__(self, parent=None):
        """Constructor."""
        super(downloaderPluginDialog, self).__init__(parent)
        self.setupUi(self)
        self.barra_progresso.setVisible(True) 
        self.barra_progresso.setValue(0)
        self._buttons_config()

    def _buttons_config(self):
        self.botao_autorizar_download.clicked.connect(self.run_download)
        self.botao_fechar.clicked.connect(self.close)

    def _add_vector_layer(self, file_path, layer_name):
        layer = QgsVectorLayer(str(file_path), layer_name, "ogr")
        if not layer.isValid():
            print("Layer failed to load!")
            return
        QgsProject.instance().addMapLayer(layer)
    
    def _update_progress_bar(self, downloaded, total_size):
        """This function is called by the Downloader class."""
        if total_size:
            self.barra_progresso.setMaximum(total_size)
            self.barra_progresso.setValue(downloaded)
        else:
            self.barra_progresso.setMaximum(0)
            self.barra_progresso.setValue(0)
            
        QApplication.processEvents()

    def run_download(self):
        self.barra_progresso.setVisible(True)
        url = self.campo_url.text()
        path = self.campo_pasta.filePath()
        file_name = self.campo_nome_arquivo.text()

        if file_name == "":
            downloader = Downloader(url, path)
        else:
            downloader = Downloader(url, path, file_name)
        downloader.download_file(progress_callback=self._update_progress_bar)

        if self.checkbox_adicionar_camada.isChecked():
            full_path = downloader._get_destination_path()     
            name = file_name if file_name else "Downloaded Layer"
            self._add_vector_layer(full_path, name)
        
        self.barra_progresso.setVisible(False)